"""Single configuration file for the clean RGB-only ZoomNeXt PNet."""

cfg = dict(
    experiment=dict(
        name="ZoomNeXt_PNet_F20_clean",
        seed=2024,
        output_dir="./outputs_clean/PNet_F20",
    ),
    data=dict(
        image_dir="./data/Train/Imgs",
        image_suffix=".jpg",
        mask_dir="./data/Train/GT",
        mask_suffix=".png",
        # Consume the exact files generated by anet_main.py. Never resample here.
        split_dir="./outputs_clean/ANet_F20/splits",
        pseudo_mask_dir="./outputs_clean/ANet_F20/pseudo_mask",
        pseudo_edge_dir="./outputs_clean/ANet_F20/pseudo_edge",
        # Optional per-pixel confidence maps; None means all pseudo pixels weight 1.
        pseudo_confidence_dir=None,
        pseudo_suffix=".png",
    ),
    model=dict(
        backbone_name="pvt_v2_b2",
        pretrained=True,
        channels=64,
        scale_factors=(1.5, 1.0, 0.5),
        siu_groups=4,
        rgpu_groups=4,
        gradient_checkpointing=False,
        # "none": mask only.
        # "aux": auxiliary predicted edge, still image-only inference.
        # "sobel": derive an edge cue internally from RGB and also predict an edge.
        edge_mode="aux",
    ),
    train=dict(
        image_size=384,
        epochs=100,
        batch_size_labeled=2,
        batch_size_pseudo=8,
        num_workers=4,
        augment=True,
        amp=True,
        optimizer="adamw",
        lr=1e-4,
        backbone_lr_scale=0.1,
        weight_decay=1e-4,
        warmup_epochs=5,
        min_lr=1e-6,
        grad_clip=0.5,
        mask_level_weights=(0.0625, 0.125, 0.25, 0.5, 1.0),
        labeled_loss_weight=1.0,
        pseudo_loss_weight=1.0,
        edge_loss_weight=1.0,
        # Pseudo boundaries are noisy; default does not supervise them.
        pseudo_edge_weight=0.0,
        ual_loss_weight=0.0,
        validate_every=1,
        # False: train on labeled_train and select with labeled_val.
        # True: train on labeled_all and save the last epoch (final retraining only).
        final_fit=False,
    ),
    test=dict(
        image_size=384,
        batch_size=8,
        num_workers=4,
        datasets=dict(
            CHAMELEON=dict(
                image_dir="./data/Test/CHAMELEON/Image",
                image_suffix=".jpg",
                mask_dir="./data/Test/CHAMELEON/Mask",
                mask_suffix=".png",
            ),
            CAMO=dict(
                image_dir="./data/Test/CAMO-TE/Image",
                image_suffix=".jpg",
                mask_dir="./data/Test/CAMO-TE/Mask",
                mask_suffix=".png",
            ),
            COD10K=dict(
                image_dir="./data/Test/COD10K-TE/Image",
                image_suffix=".jpg",
                mask_dir="./data/Test/COD10K-TE/Mask",
                mask_suffix=".png",
            ),
            NC4K=dict(
                image_dir="./data/Test/NC4K/Image",
                image_suffix=".jpg",
                mask_dir="./data/Test/NC4K/Mask",
                mask_suffix=".png",
            ),
        ),
    ),
)
